### ISSUE TITLE
Comments on the blog post

### ISSUE THREAD

**Issue by nfrankel** [hazelcast-guides/springboot-tomcat-session-replication-on-kubernetes#2]
Thanks for the content @alparslanavci.

Here are my comments:

* Please check if you can rework the headers and their hierarchy. Requirements is H1 and is 3 lines long, while the other H1 header has the rest of the content
* Conclusion => great!
* An introduction would be great as well. I suggest you tell about the context, the problem that it causes, and then introduce session replication as a possible solution. You might mention other alternatives (or even session replication with Spring Session) - but at least mention they exist
* Up to you, but I'd use different branches instead of different folders (initial vs. final)
* Since it will be a blog post, I suggest you add link to the sources
* Finally, adding references to other blog posts/articles whether on our blog or outside would be a nice improvement (plus it adds to the SEO)

**Comment by alparslanavci** [comment]
@nfrankel thanks for the review. 

> Please check if you can rework the headers and their hierarchy. Requirements is H1 and is 3 lines long, while the other H1 header has the rest of the content

I didn't get what you mean here, can you please elaborate?
